const { Permissions } = require('detritus-client/lib/constants');
const { decimalToHexColor } = require('#utils/color');

module.exports.DISCORD_INVITES = Object.freeze({
  support: 'https://discord.gg/6C9pcD4EUq',
});

module.exports.DEFAULT_BOT_NAME = 'Meteor';

// The first prefix in this list is considered the
// default prefix and will be displayed in various
// places throughout the app
module.exports.DEFAULT_PREFIXES = ['m.', ';'];

module.exports.PRIVACY_POLICY_SECTIONS = [
  '### Summary\n- We do not store or collect information about our users or their servers.\n- We share certain data with third parties that is strictly necessary to operate certain functionality.',
  '### The information we collect\nWe use technology to log unexpected issues that may occur when interacting with our application. These logs are only shared with the developers of the application and not accessible to the public. Logged information includes:\n- Your username, server and channel\n- The command you executed, as well as its arguments (excluding images)',
  'Images modified via our proprietary api are directly uploaded to Discord and never permanently stored anywhere other than the requested channel by us.\n- The only exception to this is the art command, wallpapers generated via art will be publicly shared in the support server for anyone to view.)',
  '### Third Parties\nWe use a variety of third party products and services to operate certain functionality of our application. Information shared with third parties is strictly limited to information necessary to provide the functionality (command arguments).\nWe do not offer any functionality that shares details about users, a channel or a server with third parties and their services.',
];

module.exports.PRIVACY_POLICY_LAST_UPDATE = 1768777200000;

module.exports.SUPPORT_ARTICLES = {
  AGE_RESTRICTED_CHANNELS: 115000084051,
};

module.exports.OPEN_SOURCE_REPOSITORY_URL = 'https://github.com/meteor-discord/application';

module.exports.COLORS = Object.freeze({
  error: 16404060,
  success: 8191849,
  warning: 15708731,
  embed: 2368553,
  brand: 65381,
  nsfw: 15159978,
  incognito: 10057726,
});

module.exports.COLORS_HEX = Object.freeze({
  error: decimalToHexColor(module.exports.COLORS.error),
  success: decimalToHexColor(module.exports.COLORS.success),
  warning: decimalToHexColor(module.exports.COLORS.warning),
  embed: decimalToHexColor(module.exports.COLORS.embed),
  brand: decimalToHexColor(module.exports.COLORS.brand),
  nsfw: decimalToHexColor(module.exports.COLORS.nsfw),
  incognito: decimalToHexColor(module.exports.COLORS.incognito),
});

// Permission requirements that apply to commands
module.exports.PERMISSION_GROUPS = Object.freeze({
  // Baseline permission set for regular commands
  baseline: [
    Permissions.SEND_MESSAGES,
    Permissions.VIEW_CHANNEL,
    Permissions.USE_EXTERNAL_EMOJIS,
    Permissions.EMBED_LINKS,
    Permissions.READ_MESSAGE_HISTORY,
  ],
  // Baseline permission set for slash commands
  baseline_slash: [
    Permissions.SEND_MESSAGES,
    Permissions.EMBED_LINKS,
    // Related to using user commands
    Permissions.USE_APPLICATION_COMMANDS,
    1n << 50n, // Use external apps
  ],

  // Permissions for all commands that use attachments
  attachments: [Permissions.ATTACH_FILES],
});

module.exports.BADGE_ICONS = Object.freeze({
  bot_developer: '<:b:1263605652337463489>',
  bug_hunter: '<:b:1263605576773013616>',
  bug_hunter_lvl2: '<:b:1263607090501517372>',
  early_supporter: '<:b:1263607076173905950>',
  hypesquad_events: '<:ico_badge_hypesquad:1263607109262770338>',
  hypesquad_balance: '<:b:1263607122659119255>',
  hypesquad_bravery: '<:b:1263607134596104273>',
  hypesquad_brilliance: '<:b:1263607149721026600>',
  mod_program: '<:b:1263605447001243698> ',
  nitro: '<:b:1263607232558399631>',
  partner: '<:b:1263605756356464751>',
  staff: '<:b:1263605715688231035>',
});

// next generation icons
module.exports.ICONS = Object.freeze({
  button_user_profile_swap: '<:button_user_profile_swap:1462762197888274442>',
  button_thermometer: '<:button_thermometer:1462762201134661819>',
  button_translate: '<:button_translate:1462762199356411904>',

  /* Brands */
  brand: '<:brand:1462762202820907114>',

  /* Icon Toolkit */
  calendar: '<:calendar:1462762196609273856>',
  flag: '<:flag:1462762189298470984>',
  home: '<:home:1462762187809357834>',
  image: '<:image:1462762186345676893>',
  padlock: '<:padlock:1462762178036629701>',
  qr: '<:qr:1462762175570645052>',
  robot: '<:robot:1462762169237110795>',
  settings: '<:settings:1462762167743942799>',
  shield: '<:shield:1462762165323960407>',
  tools: '<:tools:1462762160554901637>',

  /* Discord */
  link: '<:link:1462762182922993776>',
  locale: '<:locale:1462762180989423669>',
  reply: '<:reply:1462762171657359492>',
  slash: '<:slash:1462762163969200249>',
  sticker: '<:sticker:1462762162060529737>',

  audio: '<:audio:1462762204096102400>',

  /* Users */
  user: '<:user:1462762159007338643>',
  user_king: '<:user_king:1462762157585465529>',
  user_shield: '<:user_shield:1462762155802886264>',

  arrow_right: '<:arrow_right:1462762205408923709>',
  arrow_left: '<:arrow_left:1462767021501452385>',

  exclaim_green: '<:exclaim_green:1462762195061575877>',
  exclaim_red: '<:exclaim_red:1462762193874456734>',

  information: '<:information:1462762184491798560>',
  question: '<:question:1462762173758570566>',
  warning: '<:warning:1462762154393337944>',

  /* Weds */
  weds_air_quality_0: '<:weds_air_quality_0:1462762153126793392>',
  weds_air_quality_1: '<:weds_air_quality_1:1462762151902052529>',
  weds_air_quality_2: '<:weds_air_quality_2:1462762149398056982>',
  weds_air_quality_3: '<:weds_air_quality_3:1462762147732787344>',
  weds_air_quality_4: '<:weds_air_quality_4:1462762146382483519>',

  weds_uv_index_0: '<:weds_uv_index_0:1462762144763215892>',
  weds_uv_index_1: '<:weds_uv_index_1:1462762143391944754>',
  weds_uv_index_2: '<:weds_uv_index_2:1462762141915287634>',
  weds_uv_index_3: '<:weds_uv_index_3:1462762140137033858>',
  weds_uv_index_4: '<:weds_uv_index_4:1462762138719359166>',
  weds_warning_frost: '<:weds_warning_frost:1462762135913238568>',
  weds_warning_flood: '<:weds_warning_flood:1462762137557401731>',
});

module.exports.MUSIC_PLATFORM_ICONS = Object.freeze({
  amazonStore: '1271168898603159554',
  amazonMusic: '1271168908182945842',
  appleMusic: '1271168916810498131',
  deezer: '1271168925652095097',
  itunes: '1271168933495574582',
  napster: '1271168944094318673',
  pandora: '1271168950784491601',
  soundcloud: '1271168959814832160',
  spotify: '1271168976755363840',
  tidal: '1271169001158082624',
  youtube: '1297690069485879337',
  youtubeMusic: '1297690078612553748',
});

module.exports.COMPONENT_BUTTON_ICONS = Object.freeze({
  NEXT: this.ICONS.arrow_right,
  PREVIOUS: this.ICONS.arrow_left,
  STOP: this.ICONS.shield,
  SEARCH: this.ICONS.qr,
  UNKNOWN: this.ICONS.question,
});

module.exports.GUILD_FEATURE_ICONS_REDESIGN = Object.freeze({
  ActivitiesIcon: '<:ico_d_activities:1263595238929334272>',
  AnnouncementsIcon: '<:ico_d_announcements:1263595270684545205>',
  BadgeIcon: '<:ico_d_badge:1263595290363957342>',
  BeakerIcon: '<:ico_d_beaker:1263595306184867840>',
  BillIcon: '<:ico_d_bill:1263595324090482719>',
  BoostTier3Icon: '<:iico_d_boosttier3:1263595349667352668>',
  BrowserIcon: '<:ico_d_browser:1263595374778515649>',
  ChatArrowRightIcon: '<:ico_d_chatarrowrighticon:1362501997697171487>',
  CircleQuestionIcon: '<:ico_d_circlequestion:1263595522921337025>',
  ClansIcons: '<:ico_d_clans:1271207373650006117>',
  ClockWarningIcon: '<:ico_d_clockwarning:1263595576520474714>',
  CompassIcon: '<:ico_d_compass:1263595614122409984>',
  FileUpIcon: '<:ico_d_fileupicon:1362499096518201364>',
  ForumIcon: '<:ico_d_forum:1263595652680650824> ',
  GameControllerIcon: '<:ico_d_gamecontroller:1263595688323846225>',
  GifIcon: '<:ico_d_gif:1263595715129643129>',
  GlobeEarthIcon: '<:ico_d_globeearth:1263595760054960161>',
  GroupIcon: '<:ico_d_group:1263595799275770007>',
  HeadphonesIcon: '<:ico_d_headphonesicon:1362498276447752435>',
  HomeIcon: '<:ico_d_home:1263596088821026938>',
  HubIcon: '<:ico_d_hub:1263596112229568512>',
  ImageIcon: '<:ico_d_imageicon:1362502720635797555>',
  ImagesIcon: '<:ico_d_images:1263596134061051935>',
  LinkIcon: '<:ico_d_link:1263596153434407032>',
  NewUserLargeIcon: '<:ico_d_newuserlarge:1263596178725933137>',
  PaintbrushThickIcon: '<:ico_d_paintbrushthick:1263596221524869164>',
  PartnerIcon: '<:ico_dc_partnerflowerbadge:1263601192643199077>',
  PencilSparkleIcon: '<:ico_d_pencilsparkleicon:1362500937859596419>',
  PiggyBankIcon: '<:ico_d_piggybank:1263596275853688944>',
  ReactionIcon: '<:ico_d_reaction:1263596296544194703>',
  RobotIcon: '<:ico_d_robot:1263596312314777782>',
  ServerIcon: '<:ico_d_server:1263596330400354314>',
  ShieldIcon: '<:ico_d_shield:1263596397924712570>',
  ShieldUserIcon: '<:ico_d_shielduser:1263596413829386292>',
  SignPostIcon: '<:ico_d_signpost:1263596376554737674>',
  SlashBoxIcon: '<:ico_d_slashbox:1263596429432328273>',
  SoundboardIcon: '<:ico_d_soundboard:1263596446301683825>',
  SparklesIcon: '<:ico_d_sparkles:1263596462764462192>',
  StaffBadgeIcon: '<:ico_d_staffbadge:1263596482519502868>',
  StageIcon: '<:ico_d_stageicon:1362498165202227270>',
  SuperReactionIcon: '<:ico_d_superreaction:1263596497283579957>',
  TagIcon: '<:ico_d_tag:1263596510994501745>',
  TextIcon: '<:ico_d_text:1263596525288685579>',
  ThreadIcon: '<:ico_d_thread:1263596544486146068>',
  TicketIcon: '<:ico_d_ticket:1263596560172716103>',
  TopicsIcon: '<:ico_d_topics:1263596574978867240>',
  TreehouseIcon: '<:ico_d_treehouse:1263596587763105843>',
  UserIcon: '<:ico_d_user:1263596600891281510>',
  UserPlusIcon: '<:ico_d_userplus:1263596620059246752>',
  UserShieldIcon: '<:ico_d_usershield:1263596641450066051>',
  VerifiedIcon: '<:ico_dc_verifiedflowerbadge:1263600898685272184>',
  VideoIcon: '<:ico_d_videoicon:1362498220994855077>',
  VoiceIcon: '<:ico_d_voicenormal:1263596678087446548>',
});

// This list should be synced with https://docs.discord.food/resources/guild#guild-features
module.exports.GUILD_FEATURES = Object.freeze({
  ACTIVITIES_ALPHA: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  ACTIVITIES_EMPLOYEE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  ACTIVITIES_INTERNAL_DEV: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  ACTIVITY_FEED_DISABLED_BY_USER: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GameControllerIcon },
  ACTIVITY_FEED_ENABLED_BY_USER: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GameControllerIcon },
  AGE_VERIFICATION_LARGE_GUILD: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  ANIMATED_BANNER: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GifIcon },
  ANIMATED_ICON: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GifIcon },
  AUDIO_BITRATE_128_KBPS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HeadphonesIcon, label: 'Audio Bitrate 128kbps' },
  AUDIO_BITRATE_256_KBPS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HeadphonesIcon, label: 'Audio Bitrate 256kbps' },
  AUDIO_BITRATE_384_KBPS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HeadphonesIcon, label: 'Audio Bitrate 384kbps' },
  AUTO_MODERATION: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon, label: 'Automod' },
  BANNER: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ImagesIcon, label: 'Server Banner' },
  BFG: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon, label: 'Really Big Server' },
  BOT_DEVELOPER_EARLY_ACCESS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.RobotIcon },
  BYPASS_SLOWMODE_PERMISSION_MIGRATION_COMPLETE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  CHANNEL_EMOJIS_GENERATED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  CHANNEL_ICON_EMOJIS_GENERATED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  COMMERCE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon, label: 'Store Channels' },
  COMMUNITY: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon },
  COMMUNITY_CANARY: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon },
  COMMUNITY_EXP_LARGE_GATED: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon,
    label: 'Communities, Large Gated Server',
  },
  COMMUNITY_EXP_LARGE_UNGATED: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon,
    label: 'Communities, Large Ungated Server',
  },
  COMMUNITY_EXP_MEDIUM: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon, label: 'Communities, Medium Server' },
  CONSIDERED_EXTERNALLY_DISCOVERABLE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  CREATOR_MONETIZABLE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  CREATOR_MONETIZABLE_DISABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  CREATOR_MONETIZABLE_PENDING_NEW_OWNER_ONBOARDING: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  CREATOR_MONETIZABLE_PROVISIONAL: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  CREATOR_MONETIZABLE_RESTRICTED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  CREATOR_MONETIZABLE_WHITEGLOVE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  CREATOR_MONETIZATION_APPLICATION_ALLOWLIST: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  CREATOR_STORE_PAGE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BrowserIcon },
  DEVELOPER_SUPPORT_SERVER: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.RobotIcon },
  DISCOVERABLE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  DISCOVERABLE_DISABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  ENABLED_DISCOVERABLE_BEFORE: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon,
    label: 'Discovery previously enabled',
  },
  ENABLED_MODERATION_EXPERIENCE_FOR_NON_COMMUNITY: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  ENHANCED_ROLE_COLORS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.PencilSparkleIcon, label: 'Gradient Role Colors' },
  EXPOSED_TO_ACTIVITIES_WTP_EXPERIMENT: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  FORWARDING_DISABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ChatArrowRightIcon },
  GAME_SERVER_HOSTING: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon },
  GAME_SERVERS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon },
  GUESTS_ENABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GroupIcon },
  GUILD_ONBOARDING: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.NewUserLargeIcon, label: 'Onboarding' },
  GUILD_ONBOARDING_EVER_ENABLED: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.NewUserLargeIcon,
    label: 'Onboarding previously enabled',
  },
  GUILD_ONBOARDING_HAS_PROMPTS: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.NewUserLargeIcon,
    label: 'Onboarding has prompts',
  },
  GUILD_PRODUCTS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.PiggyBankIcon, label: 'Server Products' },
  GUILD_PRODUCTS_ALLOW_ARCHIVED_FILE: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.PiggyBankIcon,
    label: 'Server Products: Archive Files',
  },
  GUILD_SERVER_GUIDE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SignPostIcon, label: 'Server Guide' },
  GUILD_TAGS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon, label: 'Server Tags' },
  GUILD_TAGS_BADGE_PACK_FLEX: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon, label: 'Server Tags: Flex Pack' },
  GUILD_TAGS_BADGE_PACK_PETS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon, label: 'Server Tags: Pets Pack' },
  GUILD_WEB_PAGE_VANITY_URL: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.GlobeEarthIcon,
    label: 'Server Web Page Vanity URL',
  },
  HAD_EARLY_ACTIVITIES_ACCESS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  HAS_DIRECTORY_ENTRY: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HubIcon },
  HIDE_FROM_EXPERIMENT_UI: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BeakerIcon },
  HUB: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HubIcon, label: 'Student Hub' },
  INCREASED_THREAD_LIMIT: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  INTERNAL_EMPLOYEE_ONLY: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.StaffBadgeIcon },
  INVITE_SPLASH: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ImagesIcon },
  INVITES_DISABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.LinkIcon },
  LINKED_TO_HUB: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HubIcon },
  MAX_FILE_SIZE_50_MB: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.FileUpIcon },
  MAX_FILE_SIZE_100_MB: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.FileUpIcon },
  MEMBER_VERIFICATION_GATE_ENABLED: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserShieldIcon,
    label: 'Membership Screening',
  },
  MEMBER_VERIFICATION_MANUAL_APPROVAL: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserShieldIcon,
    label: 'Membership Screening Manual Approval',
  },
  MORE_EMOJI: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  MORE_SOUNDBOARD: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SoundboardIcon },
  MORE_STICKERS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  NEWS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.AnnouncementsIcon, label: 'Announcement Channels' },
  NON_COMMUNITY_RAID_ALERTS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  PARTNERED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.PartnerIcon },
  PIN_PERMISSION_MIGRATION_COMPLETE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  PREMIUM_TIER_3_OVERRIDE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BoostTier3Icon },
  PREVIEW_ENABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  PRODUCTS_AVAILABLE_FOR_PURCHASE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon },
  RAID_ALERTS_DISABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  RELAY_ENABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon },
  REPORT_TO_MOD_PILOT: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  REPORT_TO_MOD_SURVEY: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  ROLE_ICONS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldUserIcon },
  ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon },
  ROLE_SUBSCRIPTIONS_ENABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon },
  SHARED_CANVAS_FRIENDS_AND_FAMILY_TEST: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.PaintbrushThickIcon },
  SOCIAL_LAYER_STOREFRONT: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon },
  SOUNDBOARD: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SoundboardIcon },
  STAGE_CHANNEL_VIEWERS_50: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.StageIcon },
  STAGE_CHANNEL_VIEWERS_150: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.StageIcon },
  STAGE_CHANNEL_VIEWERS_300: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.StageIcon },
  SUMMARIES_ENABLED_GA: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  SUMMARIES_DISABLED_BY_USER: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  SUMMARIES_ENABLED_BY_USER: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  SUMMARIES_LONG_LOOKBACK: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  SUMMARIES_OPT_OUT_EXPERIENCE: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  STAFF_LEVEL_COLLABORATOR_REQUIRED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.StaffBadgeIcon },
  STAFF_LEVEL_RESTRICTED_COLLABORATOR_REQUIRED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.StaffBadgeIcon },
  TIERLESS_BOOSTING: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BoostTier3Icon, label: 'New Boosting' },
  TIERLESS_BOOSTING_SYSTEM_MESSAGE: {
    icon: this.GUILD_FEATURE_ICONS_REDESIGN.BoostTier3Icon,
    label: 'New Boosting System Message',
  },
  VANITY_URL: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GlobeEarthIcon },
  VERIFIED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VerifiedIcon },
  VIDEO_BITRATE_ENHANCED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VideoIcon },
  VIDEO_QUALITY_720_60FPS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VideoIcon },
  VIDEO_QUALITY_1080_60FPS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VideoIcon },
  VIP_REGIONS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VoiceIcon },
  VOICE_IN_THREADS: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  WELCOME_SCREEN_ENABLED: { icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserPlusIcon },
});

module.exports.FUNNY_CAT_ICONS = [
  '<:ico_garf_gm:1263608611645558814>',
  '<:ico_garf_gn:1263608597179404319>',
  '<:ico_garf_funnycat:1263608584390971498>',
  '<:ico_garf_garthumbsup:1263608571929694353>',
];

module.exports.TIKTOK_VOICES_FRENCH = {
  fr_001: 'French Male 1',
  fr_002: 'French Male 2',
};

module.exports.TIKTOK_VOICES_GERMAN = {
  de_001: 'German Female',
  de_002: 'German Male',
};

module.exports.TIKTOK_VOICES_INDONESIAN = {
  id_male_darma: 'Darma',
  id_female_icha: 'Icha',
  id_female_noor: 'Noor',
  id_male_putra: 'Putra',
};

module.exports.TIKTOK_VOICES_ITALIAN = {
  it_male_m18: 'Italian Male',
};

module.exports.TIKTOK_VOICES_JAPANESE = {
  jp_001: 'Miho (美穂)',
  jp_003: 'Keiko (恵子)',
  jp_005: 'Sakura (さくら)',
  jp_006: 'Naoki (直樹)',
  jp_male_osada: 'モリスケ (Morisuke)',
  jp_male_matsuo: 'モジャオ (Matsuo)',
  jp_female_machikoriiita: 'まちこりーた (Machikoriiita)',
  jp_male_matsudake: ' マツダ家の日常 (Matsudake)',
  jp_male_shuichiro: '修一朗 (Shuichiro)',
  jp_female_rei: '丸山礼 (Maruyama Rei)',
  jp_male_hikakin: 'ヒカキン (Hikakin)',
  jp_female_yagishaki: '八木沙季 (Yagi Saki)',
};

module.exports.TIKTOK_VOICES_KOREAN = {
  kr_002: 'Korean Male 1',
  kr_004: 'Korean Male 2',
  kr_003: 'Korean Female',
};

module.exports.TIKTOK_VOICES_PORTUGESE = {
  br_003: 'Júlia',
  br_004: 'Ana',
  br_005: 'Lucas',
  pt_female_lhays: 'Lhays Macedo',
  pt_female_laizza: 'Laizza',
};

module.exports.TIKTOK_VOICES_SPANISH = {
  es_002: 'Spanish Male',
  es_male_m3: 'Julio',
  es_female_f6: 'Alejandra',
  es_female_pb1: 'Mariana',
  es_mx_002: 'Álex (Warm)',
  es_mx_female_supermom: 'Super Mamá',
};

module.exports.TIKTOK_VOICES_SONG = {
  en_male_m2_xhxs_m03_silly: 'Song: Quirky Time',
  en_female_f08_twinkle: 'Song: Pop Lullaby',
  en_male_m03_sunshine_soon: 'Song: Toon Beat (Sunshine Soon)',
  en_male_sing_funny_thanksgiving: 'Song: Thanksgiving',
  en_female_ht_f08_newyear: 'Song: NYE 2023',
  en_female_ht_f08_wonderful_world: 'Song: Melodrama (Wonderful World)',
  en_male_m03_lobby: 'Song: Jingle (Lobby)',
  en_male_sing_funny_it_goes_up: 'Song: Hypetrain (It Goes Up)',
  en_female_ht_f08_glorious: 'Song: Euphoric (Glorious)',
  en_female_ht_f08_halloween: 'Song: Opera (Halloween)',
  en_female_f08_warmy_breeze: 'Song: Open Mic (Warmy Breeze)',
  en_male_m2_xhxs_m03_christmas: 'Song: Cozy',
  en_female_f08_salut_damour: "Song: Cottagecore (Salut d'Amour)",
  en_male_m03_classical: 'Song: Classic Electric',
  en_male_sing_deep_jingle: 'Song: Caroler',
};

module.exports.TIKTOK_VOICES_POP_CULTURE = {
  en_female_madam_leota: 'Madame Leota (Haunted Mansion)',
  en_us_rocket: 'Rocket (Guardians of the Galaxy)',
  en_us_stitch: 'Stitch (Lilo & Stitch)',
  en_us_stormtrooper: 'Stormtrooper (Star Wars)',
  en_us_c3po: 'C-3PO (Star Wars)',
  en_us_chewbacca: 'Chewbacca (Star Wars)',
  en_us_ghostface: 'Ghostface (Scream)',
  en_male_grinch: 'Trickster (Grinch)',
  en_male_ghosthost: 'Ghost Host',
  en_male_ukbutler: 'Mr. Meticulous',
  en_male_deadpool: 'Mr. GoodGuy (Deadpool)',
  //"en_male_petercullen": "Optimus Prime",
};

module.exports.TIKTOK_VOICES_CHARACTERS = {
  en_female_pansino: 'Varsity',
  //"en_male_santa_effect": "Santa (w/ effect)",
  en_male_santa: 'Santa',
  en_male_pirate: 'Pirate',
  en_male_trevor: 'Marty',
  en_male_wizard: 'Magician',
  en_male_ukneighbor: 'Lord Cringe',
  en_female_grandma: 'Grandma',
  en_female_shenna: 'Debutante',
  en_male_cupid: 'Cupid',
  //"en_female_richgirl": "Bestie",
  en_female_makeup: 'Beauty Guru',
  en_female_betty: 'Bae',
  //"en_male_santa_narration": "Author",
  en_male_jarvis: 'Alfred',
  en_male_funny: 'Wacky',
  en_male_narration: 'Story Teller',
  en_male_cody: 'Serious',
  en_female_samc: 'Empathetic',
  en_us_010: 'Confidence',
  en_us_009: 'Scientist',
  en_us_007: 'Professor',
  en_us_006: 'Joey',
  en_us_002: 'Jessie',
  en_au_002: 'Smooth (Alex)',
  en_au_001: 'Metro (Eddie)',
  en_female_emotional: 'Peaceful',
  en_uk_001: 'Narrator (Chris)',
};

module.exports.TIKTOK_VOICES = [
  { name: 'English Singing - Tenor', value: 'en_male_m03_lobby' },
  { name: 'English Singing - Alto', value: 'en_female_f08_salut_damour' },
  { name: 'English Singing - Warmy Breeze', value: 'en_female_f08_warmy_breeze' },
  { name: 'English Singing - Sunshine Soon', value: 'en_male_m03_sunshine_soon' },
  { name: 'English Narration - Normal', value: 'en_male_narration' },
  { name: 'English Narration - Funny', value: 'en_male_funny' },
  { name: 'English Narration - Emotional', value: 'en_female_emotional' },
  { name: 'English AU - Female', value: 'en_au_001' },
  { name: 'English AU - Male', value: 'en_au_002' },
  { name: 'English UK - Male', value: 'en_uk_001' },
  { name: 'English US - Female', value: 'en_us_001' },
  { name: 'English US - Male', value: 'en_us_006' },
  { name: 'Ghost Face (Disney)', value: 'en_us_ghostface' },
  { name: 'Chewbacca (Disney)', value: 'en_us_chewbacca' },
  { name: 'C3PO (Disney)', value: 'en_us_c3po' },
  { name: 'Stitch (Disney)', value: 'en_us_stitch' },
  { name: 'Stormtrooper (Disney)', value: 'en_us_stormtrooper' },
  { name: 'Rocket (Disney)', value: 'en_us_rocket' },
  { name: 'French - Male', value: 'fr_001' },
  { name: 'German - Female', value: 'de_001' },
  { name: 'German - Male', value: 'de_002' },
  { name: 'Spanish - Male', value: 'es_002' },
  { name: 'Spanish MX - Male', value: 'es_mx_002' },
];

module.exports.PLAYHT_VOICES = [{ name: 'Conrad (German)', value: 'de-DE-ConradNeural' }];

module.exports.IMTRANSLATOR_VOICES = [
  { name: 'English (Male)', value: 'en' },
  { name: 'English (Female)', value: 'enf' },
  { name: 'Chinese (Female)', value: 'zh' },
  { name: 'Spanish (Carlos)', value: 'es' },
  { name: 'Russian (Female)', value: 'ru' },
  { name: 'French (Female)', value: 'fr' },
  { name: 'German (Male)', value: 'de' },
  { name: 'Italian (Male)', value: 'it' },
  { name: 'Portugese (Female)', value: 'pt' },
  { name: 'Japanese (Female)', value: 'ja' },
  { name: 'Korean (Female)', value: 'ko' },
];

module.exports.MICROSOFT_VOICES = [
  { name: 'Microsoft Sam', value: 'Sam' },
  { name: 'BonziBUDDY', value: 'Bonzi' },
  { name: 'Mary', value: 'Mary' },
  { name: 'Mike', value: 'Mike' },
  { name: 'Robot', value: 'RoboSoft Four' },
  { name: 'Whisper (Female)', value: 'Female Whisper' },
  { name: 'Whisper (Male)', value: 'Male Whisper' },
];

module.exports.MICROSOFT_VOICE_CONFIG = {
  Sam: { pitch: 100, speed: 150 },
  Bonzi: { pitch: 140, speed: 157 },
  Mary: { pitch: 169, speed: 170 },
  Mike: { pitch: 113, speed: 170 },
  'RoboSoft Four': { pitch: 169, speed: 170 },
  'Female Whisper': { pitch: 169, speed: 170 },
  'Male Whisper': { pitch: 113, speed: 170 },
};

module.exports.REWRITE_STYLES = [
  { name: '📝 Fix Grammar', value: 'GRAMMAR' },
  { name: '🤩 Excited', value: 'EXCITED' },
  { name: '😎 Chill', value: 'CHILL' },
  { name: '📜 Shakespeare', value: 'SHAKESPEARE' },
  { name: '📰 Shorten', value: 'SHORTEN' },
  { name: '📄 Formal', value: 'FORMAL' },
];

module.exports.DICTIONARY_DEFAULT_LANGUAGES = Object.freeze([
  'en',
  'en-uk',
  'de',
  'fr',
  'es',
  'pt',
  'no',
  'fi',
  'sv',
  'it',
  'ja',
  'pl',
  'ru',
  'ar',
  'iw',
  'tr',
  'hi',
  'zh-cn',
  'zh-tw',
]);

module.exports.DICTIONARY_LANGUAGES = Object.freeze({
  ar: 'Arabic',
  ca: 'Catalan',
  cs: 'Czech',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  'en-uk': 'English (UK)',
  en: 'English (US)',
  es: 'Spanish',
  fi: 'Finnish',
  fr: 'French',
  hi: 'Hindi',
  hr: 'Croatian',
  id: 'Indonesian',
  it: 'Italian',
  iw: 'Hebrew',
  ja: 'Japanese',
  ko: 'Korean',
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  'pt-br': 'Portuguese (Brazil)',
  'pt-pt': 'Portuguese (Portugal)',
  pt: 'Portuguese',
  ro: 'Romanian',
  ru: 'Russian',
  sr: 'Serbian',
  sk: 'Slovak',
  sv: 'Swedish',
  th: 'Thai',
  tl: 'Tagalog',
  tr: 'Turkish',
  uk: 'Ukrainian',
  vi: 'Vietnamese',
  'zh-cn': 'Chinese',
  'zh-tw': 'Chinese',
  zh: 'Chinese',
});

// Default list of languages uses in various translate contexts
module.exports.TRANSLATE_DEFAULT_LANGUAGE_LIST = Object.freeze([
  'en',
  'de',
  'fr',
  'es',
  'pt-PT',
  'no',
  'fi',
  'sv',
  'it',
  'ja',
  'pl',
  'ru',
  'ar',
  'he',
  'tr',
  'hi',
  'zh-CN',
  'zh-TW',
]);

module.exports.TRANSLATE_AUTOCOMPLETE_HIDDEN_LANGUAGES = Object.freeze(['ja-Latn']);

// hey if you're looking at this and are annoyed that a language
// doesn't as expected work lmk on discord @bignutty and i'll add
// it (within reason), same goes for flag emoji below
module.exports.TRANSLATE_LANGUAGE_ALIASES = Object.freeze({
  jp: 'ja',
});

// there are a lot of overlapping flags (specifically in eastern territories),
// we have separata "display" and "resolve" mappings now.
module.exports.TRANSLATE_DISPLAY_MAPPINGS = Object.freeze({
  auto: this.ICONS.gs_auto_awesome,
  und: this.ICONS.gs_auto_awesome,
  af: '🇿🇦',
  sq: '🇦🇱',
  am: '🇪🇹',
  ar: '🇸🇦',
  hy: '🇦🇲',
  as: '🇮🇳',
  ay: '🇧🇴',
  az: '🇦🇿',
  bm: '🇲🇱',
  eu: '',
  be: '🇧🇾',
  bn: '🇧🇩',
  bho: '🇮🇳',
  bs: '🇧🇦',
  bg: '🇧🇬',
  ca: '',
  ceb: '🇵🇭',
  co: '',
  hr: '🇭🇷',
  cs: '🇨🇿',
  da: '🇩🇰',
  dv: '🇲🇻',
  doi: '🇮🇳',
  nl: '🇳🇱',
  en: '🇺🇸',
  eo: '',
  et: '🇪🇪',
  ee: '🇹🇬',
  fil: '🇵🇭',
  fi: '🇫🇮',
  fr: '🇫🇷',
  fy: '🇳🇱',
  gl: '🇪🇸',
  ka: '🇬🇪',
  de: '🇩🇪',
  el: '🇬🇷',
  gn: '🇵🇾',
  gu: '🇮🇳',
  ht: '🇭🇹',
  ha: '🇳🇬',
  haw: '',
  he: '🇮🇱',
  iw: '🇮🇱',
  hi: '🇮🇳',
  hmn: '',
  hu: '🇭🇺',
  is: '🇮🇸',
  ig: '🇳🇬',
  ilo: '',
  id: '🇮🇩',
  ga: '🇮🇪',
  it: '🇮🇹',
  ja: '🇯🇵',
  'ja-Latn': '🇯🇵',
  jv: '🇮🇩',
  kn: '🇮🇳',
  kk: '🇰🇿',
  km: '🇰🇭',
  rw: '🇷🇼',
  gom: '🇮🇳',
  ko: '🇰🇷',
  kri: '🇸🇱',
  ku: '',
  ckb: '',
  ky: '🇰🇬',
  lo: '🇱🇦',
  la: '',
  lv: '🇱🇻',
  ln: '🇨🇩',
  lt: '🇱🇹',
  lg: '🇺🇬',
  lb: '🇱🇺',
  mk: '🇲🇰',
  mai: '🇮🇳',
  mg: '🇲🇬',
  ms: '🇲🇾',
  ml: '🇮🇳',
  mt: '🇲🇹',
  mi: '🇳🇿',
  mr: '🇮🇳',
  mn: '🇲🇳',
  my: '🇲🇲',
  ne: '🇳🇵',
  no: '🇳🇴',
  ny: '🇲🇼',
  ps: '🇦🇫',
  fa: '🇮🇷',
  pl: '🇵🇱',
  pt: '🇵🇹',
  'pt-pt': '🇵🇹',
  'pt-br': '🇧🇷',
  ro: '🇷🇴',
  ru: '🇷🇺',
  sm: '🇼🇸',
  sa: '🇮🇳',
  gd: '',
  nso: '🇿🇦',
  sr: '🇷🇸',
  st: '🇱🇸',
  sn: '🇿🇼',
  si: '🇱🇰',
  sk: '🇸🇰',
  sl: '🇸🇮',
  so: '🇸🇴',
  es: '🇪🇸',
  su: '🇸🇩',
  sw: '🇰🇪',
  sv: '🇸🇪',
  tl: '🇵🇭',
  tg: '🇹🇯',
  te: '🇮🇳',
  th: '🇹🇭',
  ti: '🇪🇷',
  ts: '🇹🇴',
  tr: '🇹🇷',
  tk: '🇹🇲',
  ak: '🇬🇭',
  uk: '🇺🇦',
  ur: '🇵🇰',
  uz: '🇺🇿',
  vi: '🇻🇳',
  cy: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  xh: '🇿🇦',
  yo: '🇳🇬',
  zu: '🇿🇦',
  'zh-TW': '🇨🇳',
  zh: '🇨🇳',
  'zh-CN': '🇨🇳',
  ab: '',
  ace: '🇮🇩',
  ach: '🇺🇬',
  aa: '🇪🇹',
  alz: '🇺🇬',
  av: '🇷🇺',
  awa: '🇮🇳',
  ban: '🇮🇩',
  bal: '🇮🇷',
  bci: '🇨🇮',
  ba: '🇷🇺',
  btx: '🇮🇩',
  bts: '🇮🇩',
  bbc: '🇮🇩',
  bem: '🇿🇲',
  bew: '🇮🇩',
  bik: '🇵🇭',
  br: '🇫🇷',
  bua: '🇷🇺',
  yue: '🇭🇰',
  ch: '🇬🇺',
  ce: '🇷🇺',
  chk: '🇫🇲',
  cv: '🇷🇺',
  crh: '🇺🇦',
  'fa-AF': '🇦🇫',
  din: '🇸🇸',
  dov: '🇨🇩',
  dyu: '🇲🇱',
  dz: '🇧🇹',
  fo: '🇫🇴',
  fj: '🇫🇯',
  fon: '🇧🇯',
  fur: '🇮🇹',
  ff: '🇲🇱',
  gaa: '🇬🇭',
  cnh: '🇲🇲',
  hil: '🇵🇭',
  hrx: '🇩🇪',
  iba: '🇲🇾',
  jam: '🇯🇲',
  jw: '🇮🇩',
  kac: '🇨🇳',
  kl: '🇬🇱',
  kr: '🇳🇪',
  pam: '🇵🇭',
  kha: '🇮🇳',
  cgg: '🇺🇬',
  kg: '🇨🇩',
  ktu: '🇨🇩',
  trp: '🇮🇳',
  kv: '🇷🇺',
  ltg: '🇱🇻',
  lij: '🇮🇹',
  li: '🇳🇱',
  lmo: '🇮🇹',
  luo: '🇰🇪',
  mad: '🇮🇩',
  mak: '🇮🇩',
  'ms-Arab': '🇲🇾',
  mam: '🇬🇹',
  gv: '🇮🇲',
  mh: '🇲🇭',
  mwr: '🇮🇳',
  mfe: '🇲🇺',
  chm: '🇷🇺',
  'mni-Mtei': '🇮🇳',
  min: '🇮🇩',
  lus: '🇮🇳',
  nhe: '🇲🇽',
  'ndc-ZW': '🇿🇼',
  nr: '🇿🇼',
  new: '🇳🇵',
  'bm-Nkoo': '🇬🇳',
  nus: '🇸🇸',
  oc: '🇫🇷',
  or: '🇮🇳',
  om: '🇪🇹',
  os: '🇷🇺',
  pag: '🇵🇭',
  pap: '🇦🇼',
  'pt-PT': '🇵🇹',
  pa: '🇮🇳',
  'pa-Arab': '🇵🇰',
  kek: '🇬🇹',
  qu: '🇵🇪',
  rom: '🇷🇴',
  rn: '🇧🇮',
  se: '🇳🇴',
  sg: '🇨🇫',
  'sat-Latn': '🇮🇳',
  crs: '🇸🇨',
  shn: '🇲🇲',
  scn: '🇮🇹',
  szl: '🇵🇱',
  sd: '🇵🇰',
  sus: '🇬🇳',
  ss: '🇸🇿',
  ty: '🇵🇫',
  'ber-Latn': '🇩🇿',
  ber: '🇩🇿',
  ta: '🇮🇳',
  tt: '🇷🇺',
  tet: '🇹🇱',
  bo: '🇨🇳',
  tiv: '🇳🇬',
  tpi: '🇵🇬',
  to: '🇹🇴',
  tn: '🇧🇼',
  tcy: '🇮🇳',
  tum: '🇲🇼',
  tyv: '🇷🇺',
  udm: '🇷🇺',
  ug: '🇨🇳',
  ve: '🇿🇦',
  vec: '🇮🇹',
  war: '🇵🇭',
  wo: '🇸🇳',
  sah: '🇷🇺',
  yi: '',
  yua: '🇲🇽',
  zap: '🇲🇽',
});

module.exports.TRANSLATE_LANGUAGE_MAPPINGS = Object.freeze({
  af: '🇿🇦',
  sq: '🇦🇱',
  am: '🇪🇹',
  ar: '',
  hy: '🇦🇲',
  as: '',
  ay: '',
  az: '🇦🇿',
  bm: '',
  eu: '',
  be: '🇧🇾',
  bn: '🇧🇩',
  bho: '',
  bs: '🇧🇦',
  bg: '🇧🇬',
  ca: '',
  ceb: '🇵🇭',
  co: '',
  hr: '🇭🇷',
  cs: '🇨🇿',
  da: '🇩🇰',
  dv: '',
  doi: '',
  nl: '🇳🇱',
  en: '🇺🇸',
  eo: '',
  et: '🇪🇪',
  ee: '',
  fil: '🇵🇭',
  fi: '🇫🇮',
  fr: '🇫🇷',
  fy: '',
  gl: '',
  ka: '🇬🇪',
  de: '🇩🇪',
  el: '🇬🇷',
  gn: '',
  gu: '',
  ht: '🇭🇹',
  ha: '🇳🇬',
  haw: '',
  he: '🇮🇱',
  iw: '🇮🇱',
  hi: '🇮🇳',
  hmn: '',
  hu: '🇭🇺',
  is: '🇮🇸',
  ig: '🇳🇬',
  ilo: '',
  id: '🇮🇩',
  ga: '🇮🇪',
  it: '🇮🇹',
  ja: '🇯🇵',
  jv: '',
  kn: '',
  kk: '🇰🇿',
  km: '🇰🇭',
  rw: '',
  gom: '',
  ko: '🇰🇷',
  kri: '',
  ku: '',
  ckb: '',
  ky: '🇰🇬',
  lo: '🇱🇦',
  la: '',
  lv: '🇱🇻',
  ln: '',
  lt: '🇱🇹',
  lg: '',
  lb: '🇱🇺',
  mk: '🇲🇰',
  mai: '',
  mg: '🇲🇬',
  ms: '🇲🇾',
  ml: '',
  mt: '🇲🇹',
  mi: '🇳🇿',
  mr: '🇮🇳',
  mn: '🇲🇳',
  my: '🇲🇲',
  ne: '🇳🇵',
  no: '🇳🇴',
  ny: '🇲🇼',
  ps: '🇦🇫',
  fa: '🇮🇷',
  pl: '🇵🇱',
  pt: '🇵🇹',
  'pt-pt': '🇵🇹',
  'pt-PT': '🇵🇹',
  'pt-br': '🇧🇷',
  ro: '🇷🇴',
  ru: '🇷🇺',
  sm: '🇼🇸',
  sa: '',
  gd: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  nso: '',
  sr: '🇷🇸',
  st: '🇱🇸',
  sn: '🇿🇼',
  si: '🇱🇰',
  sk: '🇸🇰',
  sl: '🇸🇮',
  so: '🇸🇴',
  es: '🇪🇸',
  su: '🇸🇩',
  sw: '🇰🇪',
  sv: '🇸🇪',
  tl: '🇵🇭',
  tg: '🇹🇯',
  te: '🇮🇳',
  th: '🇹🇭',
  ti: '🇪🇷',
  ts: '🇹🇴',
  tr: '🇹🇷',
  tk: '🇹🇲',
  ak: '🇬🇭',
  uk: '🇺🇦',
  ur: '🇵🇰',
  uz: '🇺🇿',
  vi: '🇻🇳',
  cy: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  xh: '🇿🇦',
  yo: '🇳🇬',
  zu: '🇿🇦',
  'zh-TW': '🇨🇳',
  zh: '🇨🇳',
  'zh-CN': '🇨🇳',
});

module.exports.TRANSLATE_LANGUAGES = Object.freeze({
  // 1p auto
  auto: 'Automatic',
  // Translate API will respond with "und" if the language is unknown
  und: 'Detected Language',
  ab: 'Abkhaz',
  ace: 'Acehnese',
  ach: 'Acholi',
  aa: 'Afar',
  af: 'Afrikaans',
  sq: 'Albanian',
  alz: 'Alur',
  am: 'Amharic',
  ar: 'Arabic',
  hy: 'Armenian',
  as: 'Assamese',
  av: 'Avar',
  awa: 'Awadhi',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ban: 'Balinese',
  bal: 'Baluchi',
  bm: 'Bambara',
  bci: 'Baoulé',
  ba: 'Bashkir',
  eu: 'Basque',
  btx: 'Batak Karo',
  bts: 'Batak Simalungun',
  bbc: 'Batak Toba',
  be: 'Belarusian',
  bem: 'Bemba',
  bn: 'Bengali',
  bew: 'Betawi',
  bho: 'Bhojpuri',
  bik: 'Bikol',
  bs: 'Bosnian',
  br: 'Breton',
  bg: 'Bulgarian',
  bua: 'Buryat',
  yue: 'Cantonese',
  ca: 'Catalan',
  ceb: 'Cebuano',
  ch: 'Chamorro',
  ce: 'Chechen',
  ny: 'Chichewa',
  zh: 'Chinese (Simplified)',
  'zh-TW': 'Chinese (Traditional)',
  chk: 'Chuukese',
  cv: 'Chuvash',
  co: 'Corsican',
  crh: 'Crimean Tatar',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  'fa-AF': 'Dari',
  din: 'Dinka',
  dv: 'Divehi',
  doi: 'Dogri',
  dov: 'Dombe',
  nl: 'Dutch',
  dyu: 'Dyula',
  dz: 'Dzongkha',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  ee: 'Ewe',
  fo: 'Faroese',
  fj: 'Fijian',
  tl: 'Filipino',
  fi: 'Finnish',
  fon: 'Fon',
  fr: 'French',
  fy: 'Frisian',
  fur: 'Friulian',
  ff: 'Fulfulde',
  gaa: 'Ga',
  gl: 'Galician',
  lg: 'Ganda',
  ka: 'Georgian',
  de: 'German',
  el: 'Greek',
  gn: 'Guarani',
  gu: 'Gujarati',
  ht: 'Haitian Creole',
  cnh: 'Hakha Chin',
  ha: 'Hausa',
  haw: 'Hawaiian',
  iw: 'Hebrew',
  hil: 'Hiligaynon',
  hi: 'Hindi',
  hmn: 'Hmong',
  hu: 'Hungarian',
  hrx: 'Hunsrik',
  iba: 'Iban',
  is: 'Icelandic',
  ig: 'Igbo',
  ilo: 'Iloko',
  id: 'Indonesian',
  ga: 'Irish Gaelic',
  it: 'Italian',
  jam: 'Jamaican Patois',
  ja: 'Japanese',
  'ja-Latn': 'Japanese',
  jw: 'Javanese',
  kac: 'Jingpo',
  kl: 'Kalaallisut',
  kn: 'Kannada',
  kr: 'Kanuri',
  pam: 'Kapampangan',
  kk: 'Kazakh',
  kha: 'Khasi',
  km: 'Khmer',
  cgg: 'Kiga',
  kg: 'Kikongo',
  rw: 'Kinyarwanda',
  ktu: 'Kituba',
  trp: 'Kokborok',
  kv: 'Komi',
  gom: 'Konkani',
  ko: 'Korean',
  kri: 'Krio',
  ku: 'Kurdish (Kurmanji)',
  ckb: 'Kurdish (Sorani)',
  ky: 'Kyrgyz',
  lo: 'Lao',
  ltg: 'Latgalian',
  la: 'Latin',
  lv: 'Latvian',
  lij: 'Ligurian',
  li: 'Limburgan',
  ln: 'Lingala',
  lt: 'Lithuanian',
  lmo: 'Lombard',
  luo: 'Luo',
  lb: 'Luxembourgish',
  mk: 'Macedonian',
  mad: 'Madurese',
  mai: 'Maithili',
  mak: 'Makassar',
  mg: 'Malagasy',
  ms: 'Malay',
  'ms-Arab': 'Malay (Jawi)',
  ml: 'Malayalam',
  mt: 'Maltese',
  mam: 'Mam',
  gv: 'Manx',
  mi: 'Maori',
  mr: 'Marathi',
  mh: 'Marshallese',
  mwr: 'Marwadi',
  mfe: 'Mauritian Creole',
  chm: 'Meadow Mari',
  'mni-Mtei': 'Meiteilon (Manipuri)',
  min: 'Minang',
  lus: 'Mizo',
  mn: 'Mongolian',
  my: 'Myanmar (Burmese)',
  nhe: 'Nahuatl (Eastern Huasteca)',
  'ndc-ZW': 'Ndau',
  nr: 'Ndebele (South)',
  new: 'Nepalbhasa (Newari)',
  ne: 'Nepali',
  'bm-Nkoo': 'NKo',
  nso: 'Northern Sotho',
  no: 'Norwegian',
  nus: 'Nuer',
  oc: 'Occitan',
  or: 'Odia (Oriya)',
  om: 'Oromo',
  os: 'Ossetian',
  pag: 'Pangasinan',
  pap: 'Papiamento',
  ps: 'Pashto',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  'pt-PT': 'Portuguese (Portugal)',
  pa: 'Punjabi',
  'pa-Arab': 'Punjabi (Shahmukhi)',
  kek: "Q'eqchi'",
  qu: 'Quechua',
  rom: 'Romani',
  ro: 'Romanian',
  rn: 'Rundi',
  ru: 'Russian',
  se: 'Sami (North)',
  sm: 'Samoan',
  sg: 'Sango',
  sa: 'Sanskrit',
  'sat-Latn': 'Santali',
  gd: 'Scots Gaelic',
  sr: 'Serbian',
  st: 'Sesotho',
  crs: 'Seychellois Creole',
  shn: 'Shan',
  sn: 'Shona',
  scn: 'Sicilian',
  szl: 'Silesian',
  sd: 'Sindhi',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  so: 'Somali',
  es: 'Spanish',
  su: 'Sundanese',
  sus: 'Susu',
  sw: 'Swahili',
  ss: 'Swati',
  sv: 'Swedish',
  ty: 'Tahitian',
  tg: 'Tajik',
  'ber-Latn': 'Tamazight',
  ber: 'Tamazight (Tifinagh)',
  ta: 'Tamil',
  tt: 'Tatar',
  te: 'Telugu',
  tet: 'Tetum',
  th: 'Thai',
  bo: 'Tibetan',
  ti: 'Tigrinya',
  tiv: 'Tiv',
  tpi: 'Tok Pisin',
  to: 'Tongan',
  ts: 'Tsonga',
  tn: 'Tswana',
  tcy: 'Tulu',
  tum: 'Tumbuka',
  tr: 'Turkish',
  tk: 'Turkmen',
  tyv: 'Tuvan',
  ak: 'Twi',
  udm: 'Udmurt',
  uk: 'Ukrainian',
  ur: 'Urdu',
  ug: 'Uyghur',
  uz: 'Uzbek',
  ve: 'Venda',
  vec: 'Venetian',
  vi: 'Vietnamese',
  war: 'Waray',
  cy: 'Welsh',
  wo: 'Wolof',
  xh: 'Xhosa',
  sah: 'Yakut',
  yi: 'Yiddish',
  yo: 'Yoruba',
  yua: 'Yucatec Maya',
  zap: 'Zapotec',
  zu: 'Zulu',
  he: 'Hebrew',
  jv: 'Javanese',
  'zh-CN': 'Chinese (Simplified)',
});

module.exports.EMOJIPEDIA_PLATFORM_TYPES = [
  'apple',
  'google',
  'samsung',
  'joypixels',
  'microsoft',
  'facebook',
  'twitter',
  'whatsapp',
  'lg',
  'mozilla',
  'htc',
  'emojidex',
  'messenger',
  'softbank',
  'au-kddi',
  'docomo',
  'openmoji',
  'skype',
  'sony',
  'noto-emoji',
  'toss-face',
  'microsoft-teams',
  'animated-noto-color-emoji',
  'twitter-emoji-stickers',
  'emojipedia',
];

module.exports.EMOJIPEDIA_PLATFORM_TYPE_ALIASES = {
  fluent: 'microsoft-3D-fluent',
  twemoji: 'twitter',
  playstation: 'sony',
  ios: 'apple',
  android: 'google',
  windows: 'microsoft',
};

/**
 * Priority of the platform types that should be
 * shown (earlier on the list = first to get picked).
 * If no platform matches whatever the api provides
 * first will be used.
 *
 * Adding types to this list will also ensure they
 * are always included in the picker (if possible)
 */
module.exports.EMOJIPEDIA_PLATFORM_PRIORITY = [
  'discord',
  'twitter',
  'google',
  'noto-emoji',
  'microsoft',
  'microsoft-teams',
  // The following are only included so they always
  // show up in the selector.
  'apple',
];

module.exports.GOOGLE_CLOUD_SAFETY_LABELS_NAMES = Object.freeze({
  adult: 'Explicit Content ',
  spoof: 'Modified Image   ',
  medical: 'Medical Image    ',
  violence: 'Contains Violence',
  racy: 'Lewd Content     ',
});

module.exports.GOOGLE_CLOUD_SAFETY_LABELS = Object.freeze({
  UNKNOWN: {
    icon: 'question_large',
    name: 'Unknown      ',
  },
  VERY_UNLIKELY: {
    icon: 'exclaim_0',
    name: 'Very Unlikely',
  },
  UNLIKELY: {
    icon: 'exclaim_1',
    name: 'Unlikely     ',
  },
  POSSIBLE: {
    icon: 'exclaim_2',
    name: 'Possible     ',
  },
  LIKELY: {
    icon: 'exclaim_3',
    name: 'Likely       ',
  },
  VERY_LIKELY: {
    icon: 'exclaim_4',
    name: 'Very Likely  ',
  },
});

module.exports.MAPKIT_ACTIONS = Object.freeze({
  SEARCH: 'search',
  STATIC_MAP: 'render',
});

module.exports.REXTESTER_LANGUAGES = Object.freeze({
  bash: '38',
  node: '23',
  js: '23',
  py2: '5',
  py: '24',
  java: '4',
  lua: '14',
  ruby: '12',
  perl: '13',
  go: '20',
  kt: '43',
  rust: '46',
  php: '8',
  c: '6',
  cpp: '7',
  cs: '1',
  elixir: '41',
  swift: '37',
  bf: '44',
  scala: '21',
  haskell: '11',
});

module.exports.REXTESTER_COMPILER_ARGS = Object.freeze({
  6: '-Wall -std=gnu99 -O2 -o a.out source_file.c',
  7: '-Wall -std=c++14 -O2 -o a.out source_file.cpp',
  11: '-o a.out source_file.hs',
});

module.exports.YOUTUBE_CATEGORIES = {
  music: '10',
  animals: '15',
  sports: '17',
  travel: '19',
  gaming: '20',
  comedy: '34',
  news: '25',
  howto: '26',
  education: '27',
  science: '28',
  movies: '30',
  animation: '31',
  documentary: '35',
  horror: '39',
  fantasy: '40',
  shorts: '42',
  shows: '43',
};

// Special character that allows for fully hidden masked links on all (supported) platforms.
module.exports.HIDDEN_MASKED_LINK_CHARACTER = '󠄴';

// Allows force-displaying an incognito reason
module.exports.INCOGNITO_REASONS = Object.freeze({
  permissions: 50013,
});

/**
 * These will force the command to become "incognito".
 */
module.exports.MESSAGE_BLOCK_REASONS = Object.freeze({
  20016: {
    message: "the channel's slowmode settings",
    support_article: 360016150952,
  },
  200000: {
    message: "the server's AutoMod setup",
    support_article: 4421269296535,
  },
  50013: {
    message: "the channel's permission setup",
    support_article: 10543994968087,
  },
});

// Used by provisional accounts for the new partner SDK
module.exports.PROVISIONAL_ACCOUNT_AVATARS = Object.freeze([
  'https://discord.com/assets/cc4d3c817f9a1b57a4f2.png',
  'https://discord.com/assets/bea3e879099c0aacba64.png',
  'https://discord.com/assets/d569b695280979e11ca3.png',
  'https://discord.com/assets/0afec6e15d7c376edb17.png',
  'https://discord.com/assets/06c71afa509013e91173.png',
  'https://discord.com/assets/15a9b7ce7525b2fbe72f.png',
]);

// Omnisearch

// Anime Format Types (/omni_service/endpoints/anime.js)
module.exports.OMNI_ANIME_FORMAT_TYPES = Object.freeze({
  ANIME: 'Anime',
  TV: 'TV',
  TV_SHORT: 'TV Short',
  MOVIE: 'Movie',
  SPECIAL: 'Special',
  OVA: 'OVA',
  ONA: 'ONA',
  MUSIC: 'Music',
  MANGA: 'Manga',
  NOVEL: 'Novel',
  ONE_SHOT: 'One Shot',
});

module.exports.OMNI_MOVIE_TYPES = Object.freeze({
  movie: 'Movie',
  tv: 'TV Show',
});

// Assets

module.exports.SCREENSHOT_ASSET_REVISION = 250117;
